/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scheme "github.com/volcano-sh/agentcube/client-go/clientset/versioned/scheme"
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SnapStartsGetter has a method to return a SnapStartInterface.
// A group's client should implement this interface.
type SnapStartsGetter interface {
	SnapStarts(namespace string) SnapStartInterface
}

// SnapStartInterface has methods to work with SnapStart resources.
type SnapStartInterface interface {
	Create(ctx context.Context, snapStart *runtimev1alpha1.SnapStart, opts v1.CreateOptions) (*runtimev1alpha1.SnapStart, error)
	Update(ctx context.Context, snapStart *runtimev1alpha1.SnapStart, opts v1.UpdateOptions) (*runtimev1alpha1.SnapStart, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, snapStart *runtimev1alpha1.SnapStart, opts v1.UpdateOptions) (*runtimev1alpha1.SnapStart, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*runtimev1alpha1.SnapStart, error)
	List(ctx context.Context, opts v1.ListOptions) (*runtimev1alpha1.SnapStartList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *runtimev1alpha1.SnapStart, err error)
	SnapStartExpansion
}

// snapStarts implements SnapStartInterface
type snapStarts struct {
	*gentype.ClientWithList[*runtimev1alpha1.SnapStart, *runtimev1alpha1.SnapStartList]
}

// newSnapStarts returns a SnapStarts
func newSnapStarts(c *RuntimeV1alpha1Client, namespace string) *snapStarts {
	return &snapStarts{
		gentype.NewClientWithList[*runtimev1alpha1.SnapStart, *runtimev1alpha1.SnapStartList](
			"snapstarts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *runtimev1alpha1.SnapStart { return &runtimev1alpha1.SnapStart{} },
			func() *runtimev1alpha1.SnapStartList { return &runtimev1alpha1.SnapStartList{} },
		),
	}
}
