/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	runtimev1alpha1 "github.com/volcano-sh/agentcube/pkg/apis/runtime/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SnapStartLister helps list SnapStarts.
// All objects returned here must be treated as read-only.
type SnapStartLister interface {
	// List lists all SnapStarts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.SnapStart, err error)
	// SnapStarts returns an object that can list and get SnapStarts.
	SnapStarts(namespace string) SnapStartNamespaceLister
	SnapStartListerExpansion
}

// snapStartLister implements the SnapStartLister interface.
type snapStartLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.SnapStart]
}

// NewSnapStartLister returns a new SnapStartLister.
func NewSnapStartLister(indexer cache.Indexer) SnapStartLister {
	return &snapStartLister{listers.New[*runtimev1alpha1.SnapStart](indexer, runtimev1alpha1.Resource("snapstart").GroupResource())}
}

// SnapStarts returns an object that can list and get SnapStarts.
func (s *snapStartLister) SnapStarts(namespace string) SnapStartNamespaceLister {
	return snapStartNamespaceLister{listers.NewNamespaced[*runtimev1alpha1.SnapStart](s.ResourceIndexer, namespace)}
}

// SnapStartNamespaceLister helps list and get SnapStarts.
// All objects returned here must be treated as read-only.
type SnapStartNamespaceLister interface {
	// List lists all SnapStarts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*runtimev1alpha1.SnapStart, err error)
	// Get retrieves the SnapStart from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*runtimev1alpha1.SnapStart, error)
	SnapStartNamespaceListerExpansion
}

// snapStartNamespaceLister implements the SnapStartNamespaceLister
// interface.
type snapStartNamespaceLister struct {
	listers.ResourceIndexer[*runtimev1alpha1.SnapStart]
}
