// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pkg/agentd/driver/proto/snapshot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxSnapshotController_GetPluginInfo_FullMethodName         = "/ssi.v1alpha1.SandboxSnapshotController/GetPluginInfo"
	SandboxSnapshotController_GetPluginCapabilities_FullMethodName = "/ssi.v1alpha1.SandboxSnapshotController/GetPluginCapabilities"
	SandboxSnapshotController_Probe_FullMethodName                 = "/ssi.v1alpha1.SandboxSnapshotController/Probe"
	SandboxSnapshotController_CreateSandboxSnapshot_FullMethodName = "/ssi.v1alpha1.SandboxSnapshotController/CreateSandboxSnapshot"
	SandboxSnapshotController_DeleteSandboxSnapshot_FullMethodName = "/ssi.v1alpha1.SandboxSnapshotController/DeleteSandboxSnapshot"
	SandboxSnapshotController_ListSandboxSnapshots_FullMethodName  = "/ssi.v1alpha1.SandboxSnapshotController/ListSandboxSnapshots"
	SandboxSnapshotController_GetSandboxSnapshot_FullMethodName    = "/ssi.v1alpha1.SandboxSnapshotController/GetSandboxSnapshot"
)

// SandboxSnapshotControllerClient is the client API for SandboxSnapshotController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SSI — Sandbox Snapshot Interface
// Snapshot artifact lifecycle: plugin introspection + snapshot CRUD.
type SandboxSnapshotControllerClient interface {
	GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error)
	GetPluginCapabilities(ctx context.Context, in *GetPluginCapabilitiesRequest, opts ...grpc.CallOption) (*GetPluginCapabilitiesResponse, error)
	Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResponse, error)
	CreateSandboxSnapshot(ctx context.Context, in *CreateSandboxSnapshotRequest, opts ...grpc.CallOption) (*CreateSandboxSnapshotResponse, error)
	DeleteSandboxSnapshot(ctx context.Context, in *DeleteSandboxSnapshotRequest, opts ...grpc.CallOption) (*DeleteSandboxSnapshotResponse, error)
	ListSandboxSnapshots(ctx context.Context, in *ListSandboxSnapshotsRequest, opts ...grpc.CallOption) (*ListSandboxSnapshotsResponse, error)
	GetSandboxSnapshot(ctx context.Context, in *GetSandboxSnapshotRequest, opts ...grpc.CallOption) (*GetSandboxSnapshotResponse, error)
}

type sandboxSnapshotControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxSnapshotControllerClient(cc grpc.ClientConnInterface) SandboxSnapshotControllerClient {
	return &sandboxSnapshotControllerClient{cc}
}

func (c *sandboxSnapshotControllerClient) GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginInfoResponse)
	err := c.cc.Invoke(ctx, SandboxSnapshotController_GetPluginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxSnapshotControllerClient) GetPluginCapabilities(ctx context.Context, in *GetPluginCapabilitiesRequest, opts ...grpc.CallOption) (*GetPluginCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginCapabilitiesResponse)
	err := c.cc.Invoke(ctx, SandboxSnapshotController_GetPluginCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxSnapshotControllerClient) Probe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeResponse)
	err := c.cc.Invoke(ctx, SandboxSnapshotController_Probe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxSnapshotControllerClient) CreateSandboxSnapshot(ctx context.Context, in *CreateSandboxSnapshotRequest, opts ...grpc.CallOption) (*CreateSandboxSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSandboxSnapshotResponse)
	err := c.cc.Invoke(ctx, SandboxSnapshotController_CreateSandboxSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxSnapshotControllerClient) DeleteSandboxSnapshot(ctx context.Context, in *DeleteSandboxSnapshotRequest, opts ...grpc.CallOption) (*DeleteSandboxSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSandboxSnapshotResponse)
	err := c.cc.Invoke(ctx, SandboxSnapshotController_DeleteSandboxSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxSnapshotControllerClient) ListSandboxSnapshots(ctx context.Context, in *ListSandboxSnapshotsRequest, opts ...grpc.CallOption) (*ListSandboxSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSandboxSnapshotsResponse)
	err := c.cc.Invoke(ctx, SandboxSnapshotController_ListSandboxSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxSnapshotControllerClient) GetSandboxSnapshot(ctx context.Context, in *GetSandboxSnapshotRequest, opts ...grpc.CallOption) (*GetSandboxSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSandboxSnapshotResponse)
	err := c.cc.Invoke(ctx, SandboxSnapshotController_GetSandboxSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxSnapshotControllerServer is the server API for SandboxSnapshotController service.
// All implementations must embed UnimplementedSandboxSnapshotControllerServer
// for forward compatibility.
//
// SSI — Sandbox Snapshot Interface
// Snapshot artifact lifecycle: plugin introspection + snapshot CRUD.
type SandboxSnapshotControllerServer interface {
	GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error)
	GetPluginCapabilities(context.Context, *GetPluginCapabilitiesRequest) (*GetPluginCapabilitiesResponse, error)
	Probe(context.Context, *ProbeRequest) (*ProbeResponse, error)
	CreateSandboxSnapshot(context.Context, *CreateSandboxSnapshotRequest) (*CreateSandboxSnapshotResponse, error)
	DeleteSandboxSnapshot(context.Context, *DeleteSandboxSnapshotRequest) (*DeleteSandboxSnapshotResponse, error)
	ListSandboxSnapshots(context.Context, *ListSandboxSnapshotsRequest) (*ListSandboxSnapshotsResponse, error)
	GetSandboxSnapshot(context.Context, *GetSandboxSnapshotRequest) (*GetSandboxSnapshotResponse, error)
	mustEmbedUnimplementedSandboxSnapshotControllerServer()
}

// UnimplementedSandboxSnapshotControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxSnapshotControllerServer struct{}

func (UnimplementedSandboxSnapshotControllerServer) GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (UnimplementedSandboxSnapshotControllerServer) GetPluginCapabilities(context.Context, *GetPluginCapabilitiesRequest) (*GetPluginCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginCapabilities not implemented")
}
func (UnimplementedSandboxSnapshotControllerServer) Probe(context.Context, *ProbeRequest) (*ProbeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Probe not implemented")
}
func (UnimplementedSandboxSnapshotControllerServer) CreateSandboxSnapshot(context.Context, *CreateSandboxSnapshotRequest) (*CreateSandboxSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSandboxSnapshot not implemented")
}
func (UnimplementedSandboxSnapshotControllerServer) DeleteSandboxSnapshot(context.Context, *DeleteSandboxSnapshotRequest) (*DeleteSandboxSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSandboxSnapshot not implemented")
}
func (UnimplementedSandboxSnapshotControllerServer) ListSandboxSnapshots(context.Context, *ListSandboxSnapshotsRequest) (*ListSandboxSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSandboxSnapshots not implemented")
}
func (UnimplementedSandboxSnapshotControllerServer) GetSandboxSnapshot(context.Context, *GetSandboxSnapshotRequest) (*GetSandboxSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSandboxSnapshot not implemented")
}
func (UnimplementedSandboxSnapshotControllerServer) mustEmbedUnimplementedSandboxSnapshotControllerServer() {
}
func (UnimplementedSandboxSnapshotControllerServer) testEmbeddedByValue() {}

// UnsafeSandboxSnapshotControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxSnapshotControllerServer will
// result in compilation errors.
type UnsafeSandboxSnapshotControllerServer interface {
	mustEmbedUnimplementedSandboxSnapshotControllerServer()
}

func RegisterSandboxSnapshotControllerServer(s grpc.ServiceRegistrar, srv SandboxSnapshotControllerServer) {
	// If the following call panics, it indicates UnimplementedSandboxSnapshotControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxSnapshotController_ServiceDesc, srv)
}

func _SandboxSnapshotController_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxSnapshotControllerServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxSnapshotController_GetPluginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxSnapshotControllerServer).GetPluginInfo(ctx, req.(*GetPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxSnapshotController_GetPluginCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxSnapshotControllerServer).GetPluginCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxSnapshotController_GetPluginCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxSnapshotControllerServer).GetPluginCapabilities(ctx, req.(*GetPluginCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxSnapshotController_Probe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxSnapshotControllerServer).Probe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxSnapshotController_Probe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxSnapshotControllerServer).Probe(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxSnapshotController_CreateSandboxSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxSnapshotControllerServer).CreateSandboxSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxSnapshotController_CreateSandboxSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxSnapshotControllerServer).CreateSandboxSnapshot(ctx, req.(*CreateSandboxSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxSnapshotController_DeleteSandboxSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSandboxSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxSnapshotControllerServer).DeleteSandboxSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxSnapshotController_DeleteSandboxSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxSnapshotControllerServer).DeleteSandboxSnapshot(ctx, req.(*DeleteSandboxSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxSnapshotController_ListSandboxSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxSnapshotControllerServer).ListSandboxSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxSnapshotController_ListSandboxSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxSnapshotControllerServer).ListSandboxSnapshots(ctx, req.(*ListSandboxSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxSnapshotController_GetSandboxSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxSnapshotControllerServer).GetSandboxSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxSnapshotController_GetSandboxSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxSnapshotControllerServer).GetSandboxSnapshot(ctx, req.(*GetSandboxSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxSnapshotController_ServiceDesc is the grpc.ServiceDesc for SandboxSnapshotController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxSnapshotController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ssi.v1alpha1.SandboxSnapshotController",
	HandlerType: (*SandboxSnapshotControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPluginInfo",
			Handler:    _SandboxSnapshotController_GetPluginInfo_Handler,
		},
		{
			MethodName: "GetPluginCapabilities",
			Handler:    _SandboxSnapshotController_GetPluginCapabilities_Handler,
		},
		{
			MethodName: "Probe",
			Handler:    _SandboxSnapshotController_Probe_Handler,
		},
		{
			MethodName: "CreateSandboxSnapshot",
			Handler:    _SandboxSnapshotController_CreateSandboxSnapshot_Handler,
		},
		{
			MethodName: "DeleteSandboxSnapshot",
			Handler:    _SandboxSnapshotController_DeleteSandboxSnapshot_Handler,
		},
		{
			MethodName: "ListSandboxSnapshots",
			Handler:    _SandboxSnapshotController_ListSandboxSnapshots_Handler,
		},
		{
			MethodName: "GetSandboxSnapshot",
			Handler:    _SandboxSnapshotController_GetSandboxSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/agentd/driver/proto/snapshot.proto",
}
